
const uz = {
    main : 'Bosh sahifa',
    hw: 'Uyga Vazifa',
    web: 'Web va grafik dizayn',
    teacher: "O'qituvchi:",
    lesee: "Darsni ko'rish",
    jar: 'Jarayonda',
    tug: 'Tugallangan',
    mycou: 'Mening kurslarim',
    adobe: 'Mavzu: Adobe photoshop panelining instrumentlar paneli',
    week: 'Bu haftada',
    das: 'Web dasturlash',
    pay: 'Pay',
    sesh: 'Sesh',
    shan: 'Shan',
    bar: 'Barcha kurslarimni ro’yxati',
    front: 'Frontend dasturchi',
    sert: 'Sertifikatlar',
    yu: 'Yutuqlar',
    kurs: 'Kurslar tugallandi',
    prog: 'Davom etayotgan kurslar',
    taf: 'Tafsilotlarni Ko’rish',
    tim4: 'Kurs davomiyligi 4 oy',
    tim6: 'Kurs davomiyligi 6 oy',
    cpay1: '1-oy uchun to’lov',
    cpay2: '2-oy uchun to’lov',
    cpay3: '3-oy uchun to’lov',
    cpay4: '4-oy uchun to’lov',
    cpay5: '5-oy uchun to’lov',
    cpay6: '5-oy uchun to’lov',
    payed: 'To’langan',
    nopayed: 'To’lanmagan',
    sum: 'sum',
    class: 'class',
    kurslar: 'Jami kurslar',
    progr: 'Progress'
};
const ru = {
    main: "Домашняя страница",
    hw: "Домашнее задание",
    web: "Веб и графический дизайн",
    teacher: "Учитель:",
    lesee: "Посмотреть урок",
    jar: "В ходе выполнения",
    tug: "Завершенный",
    mycou: "Мои курсы",
    adobe: "Тема: Панель инструментов панели Adobe Photoshop",
    week: "На этой неделе",
    das: "Веб-программирование",
    pay: "Чет",
    sesh: "Втор",
    shan: "Суб",
    bar: "Список всех моих курсов",
    front: "Фронтенд-разработчик",
    sert: "Сертификаты",
    yu: "Достижения",
    kurs: "Курсы завершены",
    prog: "Текущие курсы",
    taf: "Подробности",
    tim4: "Продолжительность курса 4 месяца",
    tim6: "Продолжительность курса 6 месяца",
    cpay1: "Оплата за 1-й месяц",
    cpay2: "Оплата за 2-й месяц",
    cpay3: "Оплата за 3-й месяц",
    cpay4: "Оплата за 4-й месяц",
    cpay5: "Оплата за 5-й месяц",
    cpay6: "Оплата за 6-й месяц",
    payed: "Оплаченный",
    nopayed: "Неоплаченный",
    sum: "сум",
    class: "класс",
    kurslar: "Всего курсов",
    progr: "Прогресс",
};
const eng = {
    main : 'Homepage',
    hw: 'Homework',
    web : 'Web and graphic design',
    teacher: 'Teacher:',
    lesee: "View lesson",
    jar: 'In progress',
    tug: 'Completed',
    mycou: 'My courses',
    adobe: 'Topic: Adobe Photoshop Panel Toolbar',
    week: 'This week',
    das: 'Web programming',
    pay: 'Thurs',
    sesh: 'Tues',
    shan: 'Satur',
    bar: 'List of all my courses',
    front: 'Frontend developer',
    sert: 'Certificates',
    yu: 'Achievements',
    kurs: 'Courses completed',
    prog: 'Current courses',
    taf: 'See details',
    tim4: 'Course duration 4 months',
    tim6: 'Course duration 6 months',
    cpay1: 'Payment for the 1st month',
    cpay2: 'Payment for the 2nd month',
    cpay3: 'Payment for the 3rd month',
    cpay4: 'Payment for the 4th month',
    cpay5: 'Payment for the 5th month',
    cpay6: 'Payment for the 6th month',
    payed: 'Paid',
    nopayed: 'Unpaid',
    sum: 'sum',
    class: 'class',
    kurslar: 'Total courses',
    progr: 'Progress'
};


export const languages = { uz, ru, eng };
