
const uz = {
    main : 'Bosh sahifa',
    hw: 'Uyga Vazifa',
    web: 'Web va grafik dizayn',
    teacher: "O'qituvchi:",
    lesee: "Darsni ko'rish",
    jar: 'Jarayonda',
    tug: 'Tugallangan',
    mycou: 'Mening kurslarim',
    adobe: 'Mavzu: Adobe photoshop panelining instrumentlar paneli',
    week: 'Bu haftada',
    das: 'Web dasturlash',
    pay: 'Pay',
    sesh: 'Sesh',
    shan: 'Shan',
    bar: 'Barcha kurslarimni ro’yxati',
    front: 'Frontend dasturchi',
    sert: 'Sertifikatlar',
    yu: 'Yutuqlar',
    kurs: 'Kurslar tugallandi',
    prog: 'Davom etayotgan kurslar',
    taf: 'Tafsilotlarni Ko’rish',
    tim4: 'Kurs davomiyligi 4 oy',
    tim6: 'Kurs davomiyligi 6 oy',
    cpay1: '1-oy uchun to’lov',
    cpay2: '2-oy uchun to’lov',
    cpay3: '3-oy uchun to’lov',
    cpay4: '4-oy uchun to’lov',
    cpay5: '5-oy uchun to’lov',
    cpay6: '5-oy uchun to’lov',
    payed: 'To’langan',
    nopayed: 'To’lanmagan',
    sum: 'sum',
    class: 'class',
    kurslar: 'Jami kurslar'
};
const ru = {
    main : 'Домашняя страница',
    hw: 'Домашнее задание',
    web : 'Веб и графический дизайн',
    teacher: 'Учитель:',
    lesee: "Посмотреть урок",
    jar: 'В ходе выполнения',
    tug: 'Завершенный',
    mycou: 'Мои курсы',
    adobe: 'Тема: Панель инструментов панели Adobe Photoshop',
    week: 'На этой неделе',
    das: 'Веб-программирование',
    pay: 'Чет',
    sesh: 'Втор',
    shan: 'Суб',
    bar: 'Список всех моих курсов',
    front: 'Фронтенд-разработчик',
    sert: 'Sertifikatlar',
    yu: 'Достижения',
    kurs: 'Курсы завершены',
    prog: 'Текущие курсы',
    taf: 'Смотрите подробности',
    tim4: 'Kurs davomiyligi 4 oy',
    tim6: 'Kurs davomiyligi 6 oy',
    cpay1: 'Оплата за 1-й месяц',
    cpay2: 'Оплата за 2-й месяц',
    cpay3: 'Оплата за 3-й месяц',
    cpay4: 'Оплата за 4-й месяц',
    cpay5: 'Оплата за 5-й месяц',
    cpay6: 'Оплата за 6-й месяц',
    payed: 'Оплаченный',
    nopayed: 'Неоплаченный',
    sum: 'сум',
    class: 'класс',
    kurslar: 'Всего курсов'
};


export const languages = { uz, ru };
